services:
  - type: web
    name: smartslide-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: credentials.json
    plan: free